### PR TITLE
Add a basic build pipeline

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
I am having problems building the extension (https://github.com/antoniovazquezblanco/BinDiffHelper/actions/runs/10787927400/job/29917814042).

What did I miss?

Thanks

### CODE REVIEW

**Comment by ubfx** [comment]
From a quick look at the logs I could imagine that gradle 8.1 is the problem - I remember similar issues depending on the gradle version. I'm currently using gradle 7.5. I'll take a closer look at this and try getting it to work with current gradle.

**Comment by antoniovazquezblanco** [comment]
Pinning Gradle to 7.5 produces a different error: https://github.com/antoniovazquezblanco/BinDiffHelper/actions/runs/10790052276/job/29924381614

**Comment by ubfx** [comment]
Looks like the Java version was at fault: https://github.com/ubfx/BinDiffHelper/actions/runs/10796226612

I'll check if we can get this to work on a more current gradle + java as well

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
